<?php
return [
    'event' => [
        'title' => 'Kto rządzi danymi, ten rządzi rynkiem — RST Data Meetup',
        'location' => 'Siedziba RST Software, Racławicka Biznes Centrum, Wrocław',
        'time' => '28 października 2025 · 15:30–20:30',
        'organizer' => 'RST Data Software',
        'hashtag' => '#DataEventWroclaw',
        'appLink' => 'https://dataeventwroclaw.pl/aplikacja',
        'logo' => 'https://placehold.co/600x300?text=RST+Data+Meetup',
        'organizerLogo' => 'https://placehold.co/180x120?text=RST+Software',
        'techCrewLogo' => 'https://placehold.co/180x120?text=Tech+Crew',
    ],
    'slideshow' => [
        'intervalSeconds' => 8,
    ],
    'talks' => [
        [
            'time' => '15:30',
            'title' => 'Rejestracja uczestników',
            'speaker' => 'Zespół Data Event Wrocław',
            'speakerRole' => 'Obsługa wydarzenia',
            'description' => 'Powitanie, szybka formalność przy wejściu oraz pierwsze rozmowy przy kawie i przekąskach.',
            'photo' => 'https://cdn.prod.website-files.com/6846a8e58a5f31ba4f45e475/68e58d3cedf20af0fa17313d_event-avatar-RST-Staff.png',
        ],
        [
            'time' => '16:10',
            'title' => 'Rynek analityki danych otwiera więcej drzwi niż kiedykolwiek — dlaczego firmy wciąż je zatrzaskują?',
            'speaker' => 'Krzysztof Marszałek',
            'speakerRole' => 'Head of Data · RST Data Software',
            'description' => 'Trendy, piramida dojrzałości danych i praktyczne metodyki, które zamienią inwestycje w dane w realną przewagę.',
            'photo' => 'https://cdn.prod.website-files.com/6846a8e58a5f31ba4f45e475/68e58d3cf3633bf7e69df722_event-photo-Krzysztof-Marsza%C5%82ek.png',
        ],
        [
            'time' => '16:40',
            'title' => 'Data Roadmap: łączenie biznesu z technologią, które daje realną wartość',
            'speaker' => 'Wojciech Ruszkiewicz',
            'speakerRole' => 'Business Analyst · RST Data Software',
            'description' => 'Jak zbudować cel w data, dobrać stack technologiczny i prowadzić zmianę, aby dane rzeczywiście pracowały na wyniki.',
            'photo' => 'https://cdn.prod.website-files.com/6846a8e58a5f31ba4f45e475/68e58d3c7be8dadf2ced59db_event-photo-Wojciech-Ruszkiewicz.png',
        ],
        [
            'time' => '17:10',
            'title' => 'Przerwa kawowa: czas na oddech i doładowanie baterii',
            'speaker' => 'Networking & Refreshments',
            'speakerRole' => 'Przerwa kawowa',
            'description' => 'Kawa, przekąski i okazja do rozmów z innymi uczestnikami zanim wrócimy do agendy.',
            'photo' => 'https://placehold.co/600x800?text=Coffee+Break',
        ],
        [
            'time' => '17:20',
            'title' => 'Transformacja analityki w scale-upie, który pozyskał 500 mln zł finansowania',
            'speaker' => 'Krzysztof Ławecki',
            'speakerRole' => 'Head of Analytics · Ramp Network',
            'description' => 'Historia przebudowy analityki: migracja z Tableau do Omni, data governance i zarządzanie zmianą w szybko rosnącej firmie.',
            'photo' => 'https://cdn.prod.website-files.com/6846a8e58a5f31ba4f45e475/68e58d3c7c5ecbe701449d10_event-photo-Krzysztof-%C5%81awecki.png',
        ],
        [
            'time' => '17:50',
            'title' => 'Jak zbudować agenta AI, z którym porozmawiasz o danych swojej firmy — w 20 minut i bez kodowania?',
            'speaker' => 'Daniel Gawłowski',
            'speakerRole' => 'Data Science Consultant',
            'description' => 'Praktyczny przepis na własnego asystenta AI opartego o No-Code RAG, gotowego do wdrożenia w organizacji.',
            'photo' => 'https://cdn.prod.website-files.com/6846a8e58a5f31ba4f45e475/68e58d3c7c5ecbe701449d0c_event-photo-Daniel-Gaw%C5%82owski.png',
        ],
        [
            'time' => '18:20',
            'title' => 'Jak wykorzystać AI do odkrywania tego, czego nie wiemy, że nie wiemy o naszym biznesie?',
            'speaker' => 'Mykyta Antoshchuk',
            'speakerRole' => 'Senior Sales Engineer · Snowflake',
            'description' => 'Jak agentic AI i Snowflake pomagają wychwytywać ukryte zależności, anomalie i strategiczne szanse w danych.',
            'photo' => 'https://cdn.prod.website-files.com/6846a8e58a5f31ba4f45e475/68e58d3c9c44d1779a8e262a_event-photo-Mykyta-Antoshchuk.png',
        ],
        [
            'time' => '18:50',
            'title' => 'Networking i rozmowy po prelekcjach',
            'speaker' => 'Community Time',
            'speakerRole' => 'Networking',
            'description' => 'Swobodne rozmowy, wymiana kontaktów i pomysłów z prelegentami oraz uczestnikami wydarzenia.',
            'photo' => 'https://placehold.co/600x800?text=Networking',
        ],
    ],
];
