<?php
return [
    'event' => [
        'title' => 'Kto rządzi danymi, ten rządzi rynkiem — RST Data Meetup',
        'location' => 'Siedziba RST Software, Racławicka Biznes Centrum, Wrocław',
        'time' => '28 października 2025 · 15:30–20:30',
        'organizer' => 'RST Data Software',
        'hashtag' => '#DataEventWroclaw',
        'appLink' => 'https://dataeventwroclaw.pl/aplikacja',
        'logo' => 'https://placehold.co/600x300?text=RST+Data+Meetup',
        'organizerLogo' => 'https://placehold.co/180x120?text=RST+Software',
        'techCrewLogo' => 'https://placehold.co/180x120?text=Tech+Crew',
    ],
    'slideshow' => [
        'intervalSeconds' => 8,
    ],
    'talks' => [
        [
            'time' => '15:30',
            'title' => 'Rejestracja uczestników',
            'speaker' => 'Zespół Data Event Wrocław',
            'description' => 'Powitanie, szybka formalność przy wejściu oraz pierwsze rozmowy przy kawie i przekąskach.',
            'photo' => 'https://placehold.co/600x800?text=Data+Event+Team',
        ],
        [
            'time' => '16:10',
            'title' => 'Rynek analityki danych otwiera więcej drzwi niż kiedykolwiek — dlaczego firmy wciąż je zatrzaskują?',
            'speaker' => 'Krzysztof Marszałek · RST Data Software',
            'description' => 'Trendy, piramida dojrzałości danych i praktyczne metodyki, które zamienią inwestycje w dane w realną przewagę.',
            'photo' => 'https://placehold.co/600x800?text=Krzysztof+Marszalek',
        ],
        [
            'time' => '16:40',
            'title' => 'Data Roadmap: łączenie biznesu z technologią, które daje realną wartość',
            'speaker' => 'Wojciech Ruszkiewicz · Business Analyst',
            'description' => 'Jak zbudować cel w data, dobrać stack technologiczny i prowadzić zmianę, aby dane rzeczywiście pracowały na wyniki.',
            'photo' => 'https://placehold.co/600x800?text=Wojciech+Ruszkiewicz',
        ],
        [
            'time' => '17:10',
            'title' => 'Przerwa kawowa: czas na oddech i doładowanie baterii',
            'speaker' => 'Networking & Refreshments',
            'description' => 'Kawa, przekąski i okazja do rozmów z innymi uczestnikami zanim wrócimy do agendy.',
            'photo' => 'https://placehold.co/600x800?text=Coffee+Break',
        ],
        [
            'time' => '17:20',
            'title' => 'Transformacja analityki w scale-upie, który pozyskał 500 mln zł finansowania',
            'speaker' => 'Krzysztof Ławecki · Ramp Network',
            'description' => 'Historia przebudowy analityki: migracja z Tableau do Omni, data governance i zarządzanie zmianą w szybko rosnącej firmie.',
            'photo' => 'https://placehold.co/600x800?text=Krzysztof+Lawecki',
        ],
        [
            'time' => '17:50',
            'title' => 'Jak zbudować agenta AI, z którym porozmawiasz o danych swojej firmy — w 20 minut i bez kodowania?',
            'speaker' => 'Daniel Gawłowski · Data Science Consultant',
            'description' => 'Praktyczny przepis na własnego asystenta AI opartego o No-Code RAG, gotowego do wdrożenia w organizacji.',
            'photo' => 'https://placehold.co/600x800?text=Daniel+Gawlowski',
        ],
        [
            'time' => '18:20',
            'title' => 'Jak wykorzystać AI do odkrywania tego, czego nie wiemy, że nie wiemy o naszym biznesie?',
            'speaker' => 'Mykyta Antoshchuk · Snowflake',
            'description' => 'Jak agentic AI i Snowflake pomagają wychwytywać ukryte zależności, anomalie i strategiczne szanse w danych.',
            'photo' => 'https://placehold.co/600x800?text=Mykyta+Antoshchuk',
        ],
        [
            'time' => '18:50',
            'title' => 'Networking i rozmowy po prelekcjach',
            'speaker' => 'Community Time',
            'description' => 'Swobodne rozmowy, wymiana kontaktów i pomysłów z prelegentami oraz uczestnikami wydarzenia.',
            'photo' => 'https://placehold.co/600x800?text=Networking',
        ],
    ],
];
